package Rysowanie;

public enum Tryb {
	WCZYTYWANIE, WCZYTYWANIEKONTURY, ZAPIS, PROSTOKONT, PROSTOKONTPAINT, ELIPSA, ELIPSAPAINT, WIELOKONT, WIELOKONTPAINT, OFF, ERROR, USUWANIE, EDYCJA, EDYCJAZMIANA;
	
}
